import { Router } from 'express';
import { orderController } from '../controllers/order.controller.js';
import { authMiddleware } from '../middleware/auth.middleware.js';
import { adminMiddleware } from '../middleware/admin.middleware.js';
const router = Router();
router.use(authMiddleware);
router.post('/', orderController.create);
router.get('/me', orderController.getMyOrders);
router.get('/:id', orderController.getById);
router.get('/', adminMiddleware, orderController.getAll);
router.patch('/:id/status', adminMiddleware, orderController.updateStatus);
export default router;
